In [37]:
from tensorflow.keras.preprocessing.text import one_hot

In [38]:
import tensorflow as tf
tf.__version__

'2.17.0'

In [39]:
sent = ["I am Aamil",
        "A glass of juice",
        "I am a good devveloper",
        "I am a good Ai developer",
        "Your videos are awesome"]

        

In [40]:
voc_size=10000

In [41]:
ohe=[one_hot(words,vocabulary_size)for words in sent]

In [42]:
ohe

[[4856, 57, 4318],
 [2265, 3202, 1091, 4335],
 [4856, 57, 2265, 2698, 3837],
 [4856, 57, 2265, 2698, 4938, 1755],
 [266, 1602, 4629, 4933]]

In [43]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

In [54]:
#Pre padding
sent_length=8
embedded_docs=pad_sequences(ohe,padding="pre",maxlen=sent_length)

In [55]:
print(embedded)
from tensorflow.keras.models import Sequential

[[   0    0    0    0    0 4856   57 4318]
 [   0    0    0    0 2265 3202 1091 4335]
 [   0    0    0 4856   57 2265 2698 3837]
 [   0    0 4856   57 2265 2698 4938 1755]
 [   0    0    0    0  266 1602 4629 4933]]


In [56]:
model=Sequential()
model.add(Embedding(voc_size,output_dim=10))
model.compile('adam','mse')

In [57]:
model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [58]:
model.build(input_shape=(None, sent_length))
model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)              │ (None, 8, 10)               │         100,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [59]:
embedded_docs[0]

array([   0,    0,    0,    0,    0, 4856,   57, 4318])

In [60]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 305ms/step


array([[[ 0.00938424, -0.01540196,  0.03585061, -0.00949339,
         -0.03955223,  0.0059324 , -0.01547293, -0.01089768,
         -0.03660579,  0.02634102],
        [ 0.00938424, -0.01540196,  0.03585061, -0.00949339,
         -0.03955223,  0.0059324 , -0.01547293, -0.01089768,
         -0.03660579,  0.02634102],
        [ 0.00938424, -0.01540196,  0.03585061, -0.00949339,
         -0.03955223,  0.0059324 , -0.01547293, -0.01089768,
         -0.03660579,  0.02634102],
        [ 0.00938424, -0.01540196,  0.03585061, -0.00949339,
         -0.03955223,  0.0059324 , -0.01547293, -0.01089768,
         -0.03660579,  0.02634102],
        [ 0.00938424, -0.01540196,  0.03585061, -0.00949339,
         -0.03955223,  0.0059324 , -0.01547293, -0.01089768,
         -0.03660579,  0.02634102],
        [ 0.0432819 ,  0.01935208,  0.01393259, -0.0011016 ,
          0.01183647,  0.04345114, -0.04890779, -0.00468178,
         -0.00823186, -0.03641535],
        [-0.04351727, -0.01390665, -0.03270859, -0.0